/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IPoolFactoryInterface extends ethers.utils.Interface {
  functions: {
    "flushReward(address,uint256)": FunctionFragment;
    "getPoolShare(address)": FunctionFragment;
    "getTotalTVLWeight()": FunctionFragment;
    "updateTVL(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "flushReward",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolShare",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalTVLWeight",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateTVL",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "flushReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolShare",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalTVLWeight",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updateTVL", data: BytesLike): Result;

  events: {};
}

export class IPoolFactory extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IPoolFactoryInterface;

  functions: {
    flushReward(
      user: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "flushReward(address,uint256)"(
      user: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getPoolShare(
      pool: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { amount: BigNumber }>;

    "getPoolShare(address)"(
      pool: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { amount: BigNumber }>;

    getTotalTVLWeight(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        lockedPoolTvlWeight: BigNumber;
        unlockedPoolTvlWeight: BigNumber;
      }
    >;

    "getTotalTVLWeight()"(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        lockedPoolTvlWeight: BigNumber;
        unlockedPoolTvlWeight: BigNumber;
      }
    >;

    updateTVL(
      tvl: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "updateTVL(uint256)"(
      tvl: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  flushReward(
    user: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "flushReward(address,uint256)"(
    user: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getPoolShare(pool: string, overrides?: CallOverrides): Promise<BigNumber>;

  "getPoolShare(address)"(
    pool: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getTotalTVLWeight(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & {
      lockedPoolTvlWeight: BigNumber;
      unlockedPoolTvlWeight: BigNumber;
    }
  >;

  "getTotalTVLWeight()"(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & {
      lockedPoolTvlWeight: BigNumber;
      unlockedPoolTvlWeight: BigNumber;
    }
  >;

  updateTVL(
    tvl: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "updateTVL(uint256)"(
    tvl: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    flushReward(
      user: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "flushReward(address,uint256)"(
      user: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getPoolShare(pool: string, overrides?: CallOverrides): Promise<BigNumber>;

    "getPoolShare(address)"(
      pool: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTotalTVLWeight(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        lockedPoolTvlWeight: BigNumber;
        unlockedPoolTvlWeight: BigNumber;
      }
    >;

    "getTotalTVLWeight()"(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        lockedPoolTvlWeight: BigNumber;
        unlockedPoolTvlWeight: BigNumber;
      }
    >;

    updateTVL(tvl: BigNumberish, overrides?: CallOverrides): Promise<void>;

    "updateTVL(uint256)"(
      tvl: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    flushReward(
      user: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "flushReward(address,uint256)"(
      user: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getPoolShare(pool: string, overrides?: CallOverrides): Promise<BigNumber>;

    "getPoolShare(address)"(
      pool: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTotalTVLWeight(overrides?: CallOverrides): Promise<BigNumber>;

    "getTotalTVLWeight()"(overrides?: CallOverrides): Promise<BigNumber>;

    updateTVL(
      tvl: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "updateTVL(uint256)"(
      tvl: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    flushReward(
      user: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "flushReward(address,uint256)"(
      user: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getPoolShare(
      pool: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getPoolShare(address)"(
      pool: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTotalTVLWeight(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getTotalTVLWeight()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    updateTVL(
      tvl: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "updateTVL(uint256)"(
      tvl: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
