/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";

import type { Errors } from "../Errors";

export class Errors__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Errors> {
    return super.deploy(overrides || {}) as Promise<Errors>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Errors {
    return super.attach(address) as Errors;
  }
  connect(signer: Signer): Errors__factory {
    return super.connect(signer) as Errors__factory;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Errors {
    return new Contract(address, _abi, signerOrProvider) as Errors;
  }
}

const _abi = [
  {
    inputs: [],
    name: "DEFENCE",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "EXCEEDS_MAX_ITERATION",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "LOCK_IN_BLOCK_LESS_THAN_MIN",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ONLY_AFTER_END_BLOCK",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ONLY_BEFORE_STAKING_ENDS",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ONLY_DEPOSITOR",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ONLY_DEPOSIT_OR_WITHDRAWN",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ONLY_FACTORY_CAN_CALL",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ONLY_POOLS_CAN_CALL",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ONLY_WHEN_DEPOSITED",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ONLY_WHEN_WITHDRAWN",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SHOULD_BE_MORE_THAN_CLAIMED",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SHOULD_BE_NON_ZERO",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "VESTED_TIME_NOT_REACHED",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x6103aa610026600b82828239805160001a60731461001957fe5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600436106100f45760003560e01c80637c7995f2116100965780639e093670116100705780639e093670146101be578063bbcad37d146101c6578063c051e977146101ce578063f6f2ae91146101d6576100f4565b80637c7995f2146101a65780637ec97d82146101ae578063944f2257146101b6576100f4565b806329f6a783116100d257806329f6a783146101865780633b4515241461018e57806353b01ada1461019657806366d354d91461019e576100f4565b80630de7d135146100f9578063114c10ec146101765780631a5dfb0b1461017e575b600080fd5b6101016101de565b6040805160208082528351818301528351919283929083019185019080838360005b8381101561013b578181015183820152602001610123565b50505050905090810190601f1680156101685780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b6101016101fb565b610101610218565b610101610235565b610101610252565b61010161026f565b61010161028c565b6101016102a9565b6101016102c6565b6101016102e3565b610101610300565b61010161031d565b61010161033a565b610101610357565b604051806040016040528060018152602001601b60f91b81525081565b604051806040016040528060018152602001604160f81b81525081565b604051806040016040528060018152602001603760f81b81525081565b604051806040016040528060018152602001602160f91b81525081565b604051806040016040528060018152602001601960f91b81525081565b604051806040016040528060018152602001600760fb1b81525081565b604051806040016040528060018152602001603560f81b81525081565b604051806040016040528060018152602001603160f81b81525081565b604051806040016040528060018152602001603360f81b81525081565b604051806040016040528060018152602001603960f81b81525081565b604051806040016040528060018152602001600d60fa1b81525081565b604051806040016040528060018152602001604360f81b81525081565b604051806040016040528060018152602001604560f81b81525081565b604051806040016040528060018152602001601160fa1b8152508156fea2646970667358221220bb1c3bc8b0ef4918e16019e74084a0050efdaeeec62f9fcc5f1731304016616064736f6c63430007000033";
