/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IPoolFactory } from "../IPoolFactory";

export class IPoolFactory__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPoolFactory {
    return new Contract(address, _abi, signerOrProvider) as IPoolFactory;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "flushReward",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "pool",
        type: "address",
      },
    ],
    name: "getPoolShare",
    outputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getTotalTVLWeight",
    outputs: [
      {
        internalType: "uint256",
        name: "lockedPoolTvlWeight",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "unlockedPoolTvlWeight",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tvl",
        type: "uint256",
      },
    ],
    name: "updateTVL",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
